### ISSUE TITLE
Travis CI `.build.yml` fails on Fedora but passes on Debian

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/libmateweather#109]
#### Expected behaviour
Travis CI Build results are expected to be consistent on all platforms.

#### Actual behaviour
Fails on Fedora but passes on Debian.

#### Steps to reproduce the behaviour
```yaml
after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -   cppcheck --xml --output-file=cppcheck.xml --enable=warning,style,performance,portability,information,missingInclude .
  -   cppcheck-htmlreport --title=${REPO_NAME} --file=cppcheck.xml --report-dir=cppcheck-htmlreport
  -   ./gen-index -l 20
  - fi
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     make check
  - fi
  - make distcheck
```
As you see Shell script `gen-index` runs only on Fedora.

Failing line with `git`:
```bash
# add the history results
temp_work_dir=`mktemp -d -u`
remote_url=`git config remote.origin.url`
```
and related logs:
```
++ mktemp -d -u
+ temp_work_dir=/tmp/tmp.g36HXaQ902
++ git config remote.origin.url
+ remote_url=
!!! ERROR: run command [docker exec -t libmateweather-fedora-build /rootdir/after_scripts].
The command "./docker-build --name ${DISTRO} --verbose --config .build.yml --build scripts" exited with 1.
```
#### MATE general version
1.26

#### Package version
N/A, Travis CI

#### Linux Distribution
N/A, Travis CI

#### Link to bugreport of your Distribution (requirement)
N/A, Travis CI

**Comment by raveit65** [comment]
Current builds are runnung fine https://app.travis-ci.com/github/mate-desktop/libmateweather/builds/253558792
Closing.
