### ISSUE TITLE
Unable to load weather data since 16.10.2023

### ISSUE THREAD

**Issue by MikePooh** [mate-desktop/libmateweather#121]
Also confirms [here](https://bugs.launchpad.net/ubuntu-mate/+bug/2039494)

Changing the location doesn't affect the behaviour.

**Comment by EvilrootNix** [comment]
> Also confirms [here](https://bugs.launchpad.net/ubuntu-mate/+bug/2039494)
> 
> Changing the location doesn't affect the behaviour.

Is because changed the source of data server and the mate team does not make any redirection from old url to new url

**Comment by colibris79** [comment]
@MikePooh It seems it is being reported [here](https://github.com/mate-desktop/libmateweather/pull/79#issuecomment-1765810415)

**Comment by raveit65** [comment]
Fix is merged.
master
https://github.com/mate-desktop/libmateweather/commit/0cc07f7e5163870bcc2fb7281c28e8e39c9cbc54
1.26 branch
https://github.com/mate-desktop/libmateweather/commit/b75056f5bccf506959a2075305f7e8abbb2502dd

**Comment by raveit65** [comment]
New releases for 1.26 and master branch https://github.com/mate-desktop/libmateweather/releases
