### ISSUE TITLE
aviationweather.gov METAR URL change

### ISSUE THREAD

**Issue by assen-totin** [mate-desktop/libmateweather#123]
I have a small project to collect weather data for my home location, which uses METAR data from the city's airport, pulling it from aviationweather.gov. It suddenly stopped working two days ago - and simultaneously, MATE Weather stopped working also. 

A quick look at aviationweather.gov showed they have a new web site. After some digging, the URL I switched to now looks like this:

https://aviationweather.gov/cgi-bin/data/metar.php?ids=LBSF&hours=0&format=xml

This will pull the latest METAR for the specified ICAO code in XML form (if you say format=raw you will get the plain text, but I find it more difficult to parse since some fields may be absent, depending on the actual weather).

Hope this will help bring MATE Weather back.

**Comment by raveit65** [comment]
Fix is merged.
master
https://github.com/mate-desktop/libmateweather/commit/0cc07f7e5163870bcc2fb7281c28e8e39c9cbc54
1.26 branch
https://github.com/mate-desktop/libmateweather/commit/b75056f5bccf506959a2075305f7e8abbb2502dd

**Comment by raveit65** [comment]
New releases for 1.26 and master branch https://github.com/mate-desktop/libmateweather/releases
