### ISSUE TITLE
unable to pull data again 30-Oct-2023

### ISSUE THREAD

**Issue by highflux7** [mate-desktop/libmateweather#130]
#### Expected behaviour
Mate Weather Report applet should be able to retrieve WX data

#### Actual behaviour
no data received.  suspect URL has changed again.

#### MATE general version
1.26.0

#### Package version
libmateweather.so.1.6.9,

#### Linux Distribution
UbuntuMate 22.04.3 LTS

#### Link to bugreport of your Distribution (requirement)

**Comment by raveit65** [comment]
fixed https://github.com/mate-desktop/libmateweather/releases/tag/v1.26.2
