### ISSUE TITLE
libmateweather 1.28 release source files are missing

### ISSUE THREAD

**Issue by L-U-T-i** [mate-desktop/libmateweather#132]
#### Expected behaviour
libmateweather 1.28 release files are available

#### Actual behaviour
libmateweather 1.28 release files are not available

#### MATE general version
1.28

**Comment by raveit65** [comment]
https://github.com/mate-desktop/libmateweather/releases/tag/v1.28.0

**Comment by L-U-T-i** [comment]
Thank you.
