### ISSUE TITLE
Broken icon cache update

### ISSUE THREAD

**Issue by brunodefraine** [mate-desktop/libmateweather#24]
Commit 2f2e67b broke the updating of the icon cache while installing.

Please see my comments on that commit for more info.

**Comment by infirit** [comment]
Can you confirm [1] works for you?

https://github.com/infirit/libmateweather/commit/4db2614c935047398479ae80a93d2eff8e35fc44

**Comment by infirit** [comment]
I suck at shell, ignore the previous comment. I have something working with https://github.com/mate-desktop/libmateweather/commit/f4a2f81a106a628125de2e3a11493e582d215241
