### ISSUE TITLE
weather.noaa.gov closed down, weather app useless

### ISSUE THREAD

**Issue by NuxRo** [mate-desktop/libmateweather#30]
Hi,

Apparently the weather.noaa.gov service was shut down, the applets stopped working in Gnome2 and MATE.

How can this be fixed?

**Comment by halmin** [comment]
I can access NOAA weather at http://www.noaa.gov/weather but this does not solve the problem with the Mate Weather Report Applet.  Also, LXDE is not having this problem.

**Comment by NuxRo** [comment]
LXDE might be using another provider. I know Gnome3's weather app defaults to the Norwegian Meteo service or something like that.

**Comment by monsta** [comment]
I know guys, they shut it down today or yesterday... I'm testing aviationweather.gov today, seems to work fine here: https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e. Will test it a bit more and push to master and 1.14 branches.

**Comment by monsta** [comment]
Ok, commit pushed to master and 1.14, and version 1.14.1 is released.

@clefebvre @flexiondotorg @sunweaver @raveit65 @posophe @willysr
Please push it to your distros guys, this should fix clock & weather applet issue.

**Comment by NuxRo** [comment]
Thanks monsta. Do you know if this patch could be used for Gnome2, too?

**Comment by monsta** [comment]
Yes, you can patch the same file in libgweather:
https://git.gnome.org/browse/libgweather/tree/libgweather/weather-metar.c?h=gnome-2-30

**Comment by willysr** [comment]
Thanks monsta

**Comment by halmin** [comment]
I may be missing something but it appears that Fedora 24 has not updated 
its versions of libgweather (Gnome) or libmateweather (Mate) and I can't 
patch it on my own.  Is this correct?

Thanks,

-- 
Hal Ginsberg
www.halginsberg.com

**Comment by monsta** [comment]
If you need the official update, you'll have to wait for @raveit65 (MATE maintainer for Fedora & RHEL 7) to push it to repos. Otherwise, I don't see any problems with applying the patch locally and rebuilding the package.

**Comment by halmin** [comment]
I am far from a Linux expert and I do appreciate whatever time you are 
giving me.  On my Fedora 24 system, I cannot find any file called 
weather-metar.c which is the file that I believe you changed.  I did try 
to compile libmateweather which I downloaded from github but my system 
said there is no configure file in the package.  I also did try to 
replace my old /usr/share/libmateweather with the new libmateweather 
package from github but that didn't work.  I then tried to replace the 
folder /usr/share/libmateweather/ with the libmateweather folder within 
the libmateweather package but that didn't work either.  Any other 
suggestions?

-- 
Hal Ginsberg
www.halginsberg.com

**Comment by NuxRo** [comment]
Here are some (untested) patched rpms for 

Fedora 24
http://li.nux.ro/download/nux/tmp/libmateweatherf24/

CentOS 7
http://li.nux.ro/download/nux/tmp/libmateweather7/

CentOS 6 (Gnome2)
http://li.nux.ro/download/nux/tmp/libgweather6/

**Comment by monsta** [comment]
@clefebvre @flexiondotorg @sunweaver @raveit65 @posophe @willysr
1.14.2 is released with new patch from https://bugzilla.gnome.org/770321, adapted patch is at https://github.com/mate-desktop/libmateweather/commit/c1b71893ec34a2d0ea8f85ce7f30f536f8582123.

For distro versions that have previous MATE releases (1.12.0 and earlier) you can simply squash https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e and https://github.com/mate-desktop/libmateweather/commit/c1b71893ec34a2d0ea8f85ce7f30f536f8582123 into a single patch. Sorry about the mess. :smile:

**Comment by halmin** [comment]
Has anyone had success patching libmateweather on Fedora 24?  I cannot do it.  I have tried everything I can think of.

**Comment by NuxRo** [comment]
Check above for my Fedora 24 rpm

**Comment by halmin** [comment]
I did here's the error message.

[root@localhost Downloads]# rpm -Uvih libmateweather-1.14.0-2.fc24.src.rpm libmateweather-data-1.14.0-2.fc24.noarch.rpm
warning: libmateweather-1.14.0-2.fc24.src.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
error: Failed dependencies:
	libmateweather = 1.14.0-2.fc24 is needed by libmateweather-data-1.14.0-2.fc24.noarch
Updating / installing...
   1:libmateweather-1.14.0-2.fc24     ################################# [100%]
error: unpacking of archive failed: cpio: Archive file not in header
error: libmateweather-1.14.0-2.fc24.src.rpm cannot be installed

I also tried with the nodeps flag.  See message below:

[root@localhost Downloads]# rpm -Uvih libmateweather-1.14.0-2.fc24.src.rpm libmateweather-data-1.14.0-2.fc24.noarch.rpm
warning: libmateweather-1.14.0-2.fc24.src.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
error: Failed dependencies:
	libmateweather = 1.14.0-2.fc24 is needed by libmateweather-data-1.14.0-2.fc24.noarch
Updating / installing...
   1:libmateweather-1.14.0-2.fc24     ################################# [100%]
error: unpacking of archive failed: cpio: Archive file not in header
error: libmateweather-1.14.0-2.fc24.src.rpm cannot be installed
[root@localhost Downloads]# rpm -Uvih libmateweather-1.14.0-2.fc24.src.rpm libmateweather-data-1.14.0-2.fc24.noarch.rpm --nodeps
warning: libmateweather-1.14.0-2.fc24.src.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
Preparing...                          ################################# [100%]
	package libmateweather-data-1.14.0-2.fc24.noarch is already installed
Updating / installing...
   1:libmateweather-1.14.0-2.fc24     ################################# [100%]

**Comment by NuxRo** [comment]
Install the libmateweather-1.14.0-2.fc24.x86_64.rpm, not the src.rpm ... The srpm is if you want to rebuild it yourself.

**Comment by halmin** [comment]
Error notes are below but I am using an old 32 bit Thinkpad so I don't think the patch will install since it appears to be a 64 bit.

rpm -Uvih libmateweather-1.14.0-2.fc24.x86_64.rpm 
warning: libmateweather-1.14.0-2.fc24.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 85c6cd8a: NOKEY
error: Failed dependencies:
	libc.so.6()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libc.so.6(GLIBC_2.2.5)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libc.so.6(GLIBC_2.3.4)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libc.so.6(GLIBC_2.4)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libc.so.6(GLIBC_2.7)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libgdk_pixbuf-2.0.so.0()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libgio-2.0.so.0()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libglib-2.0.so.0()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libgobject-2.0.so.0()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libgtk-x11-2.0.so.0()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libm.so.6()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libm.so.6(GLIBC_2.2.5)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libsoup-2.4.so.1()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2()(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2(LIBXML2_2.4.30)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2(LIBXML2_2.5.0)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2(LIBXML2_2.5.7)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2(LIBXML2_2.6.0)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libxml2.so.2(LIBXML2_2.6.21)(64bit) is needed by libmateweather-1.14.0-2.fc24.x86_64
	libmateweather.so.1 is needed by (installed) mate-applets-1.14.0-1.fc24.i686
	libmateweather.so.1 is needed by (installed) mate-panel-1.14.2-1.fc24.i686
[root@localhost Downloads]# dnf install libmateweather-1.14.0-2.fc24.x86_64.rpm
Failed to synchronize cache for repo 'google-chrome', disabling.
Last metadata expiration check: 0:50:42 ago on Mon Aug 29 11:12:59 2016.
Error: package libmateweather-1.14.0-2.fc24.x86_64 is not installable
(try to add '--allowerasing' to command line to replace conflicting packages)
[root@localhost Downloads]# dnf install libmateweather-1.14.0-2.fc24.x86_64.rpm --allowerasing
Failed to synchronize cache for repo 'google-chrome', disabling.
Last metadata expiration check: 0:50:57 ago on Mon Aug 29 11:12:59 2016.
Error: package libmateweather-1.14.0-2.fc24.x86_64 is not installable

**Comment by NuxRo** [comment]
Oh.. 32bit. Didn't expect this. :)
You should find the 32bit package in the same location.

**Comment by halmin** [comment]
Thanks!  This works.  But there is still no forecast provided.

**Comment by monsta** [comment]
Forecast issue is related to another URL, and I only recently learned about it from https://github.com/mate-desktop/libmateweather/issues/33. I can't test it in my location, it's simply not provided here (in Russia), so I'm currently waiting for @NuxRo to test the change I proposed there.

**Comment by halmin** [comment]
Thanks Monsta!  Great work all the way around.  I hope we can get that forecast issue resolved as well.  I do reply on my mate weather-app quite a bit.

**Comment by NuxRo** [comment]
Ok, tried Monsta's suggestion in the other issue and built new packages, they're at the same location, you're interested in the 1.14.0-3.fc24 ones.
You might need to reload the applet or logout/login from MATE.

**Comment by halmin** [comment]
Thanks NuxRo and Monsta. Everything is working now.  Amazing work.  I hope it wasn't too much trouble.

**Comment by monsta** [comment]
@clefebvre @flexiondotorg @sunweaver @raveit65 @posophe @willysr
Version 1.14.3 is released with the forecast fix (see https://github.com/mate-desktop/libmateweather/issues/33 for more info). Patch is at https://github.com/mate-desktop/libmateweather/commit/fc0d17caf15d2b88776fa27c36d5ba86555e407c.

**Comment by raveit65** [comment]
Is this the final fix or can we expect another release tomorrow?
I'm still wondering why we create 3 releases since 	2016-08-24.

**Comment by goetzc** [comment]
Better more bug fix releases that less or none.

**Comment by raveit65** [comment]
> Better more bug fix releases that less or none.
 Looks like you know how much time it cost to build a package for a distro with 4 branches ;)

**Comment by monsta** [comment]
I really hope it's the last one. I wish I knew how to fix it properly when I first discovered the bug (on 24th Aug), then it would be just one release...
