### ISSUE TITLE
Weather applet not working

### ISSUE THREAD

**Issue by Michael-AU** [mate-desktop/libmateweather#31]
The weather applet isn't working as of yesterday afternoon. This is a Linux issues not just a MATE issue. I see Monsta has already made corrections but there are more possibilities if you choose to use them.

This comes from the Trinity (TDE) mailing list and contains a different url (http://tgftp.nws.noaa.gov/data/observations/metar/stations/) to the one that Monsta patched that may be worthwhile adding as a backup.
http://mirror.git.trinitydesktop.org/cgit/tdetoys/commit/?id=eb7b432f

Cheers.
Michael.

**Comment by monsta** [comment]
Ah yes, I looked at that website. It's better as it has plain text files (less data to download and parse), but I found out it would require more changes to this legacy code... So, for a quick fix, I went with a simple patch with a drop-in replacement URL.

**Comment by Michael-AU** [comment]
While I'm waiting for Debian to bring the update into Stretch what file do I need to change on my machines to suit the new url?

**Comment by monsta** [comment]
Rebuild libmateweather with this patch: https://github.com/mate-desktop/libmateweather/commit/835055e0d0b950d3f66ad236de7e40942f6f7d8e

**Comment by Michael-AU** [comment]
Thanks Monsta, so no easy slot the new lines in a file then.
