### ISSUE TITLE
Fails to build from source with tzdata 2016g

### ISSUE THREAD

**Issue by jbicha** [mate-desktop/libmateweather#35]
libmateweather currently fails to build with tzdata 2016g.

GNOME bug: https://bugzilla.gnome.org/show_bug.cgi?id=772253
Patch I submitted to GNOME: https://bug772253.bugzilla-attachments.gnome.org/attachment.cgi?id=336668

Debian patch: https://anonscm.debian.org/git/pkg-mate/libmateweather.git/tree/debian/patches/1001_adapt-to-timezone-namechange-for-Asia-Yangon.patch

**Comment by monsta** [comment]
Thanks - but can we count on all distros getting this update? We really can't use conditional build here (for old and new name).

**Comment by monsta** [comment]
@flexiondotorg @sunweaver guys, please check out the updated patch at https://bugzilla.gnome.org/show_bug.cgi?id=772253#c5 - I think it's better as it doesn't break the translations.

**Comment by jbicha** [comment]
Yes, tzdata should be a mandatory update since it's essential that distros handle daylight savings time and other timezone changes correctly. [Ubuntu](https://launchpad.net/ubuntu/+source/tzdata) has applied 2016g to all supported releases already (vivid and wily aren't really supported).

Any distro that chooses to update MATE but not do the tzdata update can simply revert this commit although that's not recommended.

**Comment by Michael-AU** [comment]
Just wondering when this will be fixed? I have all but 3 (I think it's 3) packages built and installed but this one is required for 2 others (mate-panel has it as a dependency) so things are unusable in MATE-1.16 until this is fixed.

**Comment by monsta** [comment]
Looks like Ubuntu 14.04 and 16.04 didn't get tzdata update yet. Same in Debian Stable. And libgweather developers still didn't accept the patch upstream. So I'm not sure that we have to accept it in libmateweather right now.

In Debian Testing and Ubuntu 16.10, where tzdata is already updated, libmateweather got patched for it.

**Comment by jbicha** [comment]
@monsta Ubuntu 14.04 and 16.04 got the [tzdata update ](https://launchpad.net/ubuntu/+source/tzdata) yesterday

libgweather is a bit undermaintained now. I wouldn't let their delay in making a new release be an excuse for MATE.

**Comment by monsta** [comment]
> libgweather is a bit undermaintained now

Hmm, I have plans for migrating our applets to libgweather for 1.18 release...
Our library is maintained worse than gnome's anyway. It seems that moving to libgweather will require less effort than backporting lots of missing stuff.

**Comment by monsta** [comment]
Ok, patch merged, sorry about the delay.
