### ISSUE TITLE
Time in New Zealand

### ISSUE THREAD

**Issue by gnugr** [mate-desktop/libmateweather#38]
Can you please enter another New Zealand weather location for the Mate Clock ver 1.16?

Location name: Dunedin, Otago Region, South Island
Latitude: -45.8741
Longitude: 170.5035
I hope this code is good enough:
```
<!-- A city in New Zealand -->
<_name>Dunedin</_name>
<coordinates>-45.8741 170.5035</coordinates>
<location>
  <name>Dunedin Airport</name>
  <code>NZDN</code>
  <coordinates>-46.018741 170.6000</coordinates>
</location>
</city>
<city>
```

**Comment by monsta** [comment]
Ok, location added in https://github.com/mate-desktop/libmateweather/commit/159158633f2f8b1736099601dd892c0448fb48c6.
