### ISSUE TITLE
Add new city for Indonesia

### ISSUE THREAD

**Issue by willysr** [mate-desktop/libmateweather#39]
Please add a city for Indonesia: Yogyakarta
```
<city>
        <!-- A city in Indonesia -->
        <_name>Yogyakarta</_name>
        <coordinates>-7.803164 110.3398254</coordinates>
        <location>
          <name>Adisucipto International Airport</name>
          <code>WAAH</code>
          <tz-hint>Asia/Jakarta</tz-hint>
          <coordinates>-7.7876785 110.4295726</coordinates>
        </location>
      </city>
```

**Comment by monsta** [comment]
Ok, location added in https://github.com/mate-desktop/libmateweather/commit/3d4f163154d6cf4de634b7f1b696f04e9c7875b1 with a few corrections. Code is ```WAHH```, and tz-hint isn't needed because it's already listed there as the default before all Indonesian cities. Hope it's ok. :slightly_smiling_face:

**Comment by willysr** [comment]
Sure, i edited the original issue to include the code for that airport
