### ISSUE TITLE
Clock applet stopped showing weather (Fedora)

### ISSUE THREAD

**Issue by ssrublev** [mate-desktop/libmateweather#80]
In Fedora, MATE Clock applet stopped showing weather. In 2 Fedoras f32, desktop and laptop. Desktop was fully updated yesterday (dnf), laptop several days ago. The clock itself works as usual. Locations are setup, home location set.

**Comment by raveit65** [comment]
Opps, i lost weather data too with German locale.

**Comment by raveit65** [comment]
Would be interested to know if this is a temporarily fallout or a data change by aviationweather.gov?

**Comment by ehashman** [comment]
Wanted to report that this occurred for MATE on Linux Mint as well (I'm running Tara/19) but it seems to have resolved some time this afternoon.

**Comment by ehashman** [comment]
Per upstream bug linked above, looks like it was a data source issue and this can probably be closed.

**Comment by raveit65** [comment]
Indeed, my weather data is back.
Thanks for info.

**Comment by raveit65** [comment]
All is back to normal, closing.

**Comment by Lamieur** [comment]
This came back and I'm still seeing "Invalid field name(s) found: raw_text" in aviationweather.gov's response.

But I've removed line 559 ("fields", "raw_text",) from my libmateweather/weather-metar.c and that works - raw_text field is still there among others, so the applet now works.

**Comment by raveit65** [comment]
Ok, reopened, but we need to find out if this is a temporarily issue from aviationweather.gov or not.

**Comment by calexil** [comment]
weather is dead again

**Comment by satoshi** [comment]
Based on this reply, the issue seems temporary while they work on the primary server: https://github.com/mate-desktop/libmateweather/pull/79#issuecomment-638496648

With that said, the fix in #79 is a good one too, as (hopefully) dataserver1_3 works reliably.

**Comment by raveit65** [comment]
Nope,
i prefer a solution without updating all distros with our fix.
Let's wait on finished server work from aviationweather.gov

**Comment by ehashman** [comment]
Yeah this seems to have broken again, although I didn't notice initially because it was displaying the last cached weather data retrieved. Looking forward to seeing this fixed permanently!

**Comment by Lamieur** [comment]
I'm not pressing (works for me after all ;)), but my single-line work-around keeps working so far, and simply not specifying to receive only the raw_data field doesn't break compatibility with the previously available (and documented) API, so there's really no harm in doing that in the mean time.

I understand releasing such simple update, with the potential of being obsolete in a month or week, is pushing work on downstream maintainers. But there should be no harm in a simple commit with a work-around, maybe giving the ones who are actively looking for an interim fix for their bug report, have a patch instantly available?

**Comment by ionutr2015** [comment]
I don't understand why you couldn't do two requests and merge the results.

**Comment by satoshi** [comment]
@Lamieur the harm of not specifying the raw_data field is every request will be 5x bigger on every machine where this applet is used.  Now, #79 discusses a different approach where we'll use `dataserver1_3` endpoint instead.

#79 also discusses a way to patch your shared object file - a workaround I'm currently using myself.

**Comment by Lamieur** [comment]
> @Lamieur the harm of not specifying the raw_data field is every request will be 5x bigger on every machine where this applet is used.
From the side of my machine, that's like a hundred of bytes of traffic per hour (or less, it's surely compressed on the HTTP layer), unmeasurable difference.

I can understand not wanting to cause bandwidth uptick on aviationweather.gov's end though. Good job and thank you :)

**Comment by calexil** [comment]
FIXED

**Comment by ionutr2015** [comment]
Hurray. Weather is back on Fedora 32.

**Comment by raveit65** [comment]
All systems on GO again.
