### ISSUE TITLE
No weather data on Manjaro Mate Edition

### ISSUE THREAD

**Issue by Kkeller83** [mate-desktop/libmateweather#81]
#### Expected behaviour
Add weather to Mate Panel. Pick city. Click on refresh. See weather.

#### Actual behaviour
Clicking on refresh after picking city. No weather data.

#### Steps to reproduce the behaviour
Add weather to Mate Panel. Pick city. Click on refresh. See no weather data.

#### MATE general version
1.24 on Manjaro

I recompiled libmateweather from source from git today with no luck., 

#### Package version
latest / bleeding edge

#### Linux Distribution
Manjaro

**Comment by raveit65** [comment]
see https://github.com/mate-desktop/libmateweather/issues/80
