### ISSUE TITLE
Missing TLS certificate verification

### ISSUE THREAD

**Issue by mcatanzaro** [mate-desktop/libmateweather#96]
Hi, I see libmateweather is using https:// URIs, but weather.c does not appear to be enabling TLS certificate verification on the SoupSessionAsync object it creates. [You have to do this manually when using the deprecated SoupSessionAsync.](https://blogs.gnome.org/mcatanzaro/2021/05/25/reminder-soupsessionsync-and-soupsessionasync-default-to-no-tls-certificate-verification/)

This was fixed in libgweather in https://gitlab.gnome.org/GNOME/libgweather/-/commit/e9358ac6a8eba9c95d139daade5c6dc1a73e679e as part of a compiler warning cleanup.

**Comment by raveit65** [comment]
Thanks for the hint, but what does exactly fix ths issue beside from deprecation fixes?

**Comment by mcatanzaro** [comment]
> Thanks for the hint, but what does exactly fix this issue beside from deprecation fixes?

With SoupSessionAsync, you are responsible for manually enabling TLS certificate verification. In contrast, the modern SoupSession class is secure by default.

**Comment by raveit65** [comment]
Yes, but that causes another problem https://github.com/mate-desktop/libmateweather/commit/50aec09eae07b0c43c10d3212a5c0e0590db57b0
So this was reverted one year ago.

**Comment by lukefromdc** [comment]
That problem was an ugly  one too: "Segfault on adding new location to calendar"

**Comment by muktupavels** [comment]
I think you are misunderstanding this issue... It is not about fixing fixing deprecation warning.

The problem is missing **TLS certificate verification**. To fix this you can switch from deprecated `SoupSessionAsync` to `SoupSession` or simply enable TLS certificate verification. From quick look `g_object_set (G_OBJECT (info->session), "ssl-use-system-ca-file", TRUE, NULL);` might be enough, check documentation.

**Comment by raveit65** [comment]
> I think you are misunderstanding this issue... It is not about fixing fixing deprecation warning.

I think everybody in this report understand this. No need to generate noise to everybody......without giving the name of the person you are addressing.
> 
> The problem is missing **TLS certificate verification**. To fix this you can switch from deprecated `SoupSessionAsync` to `SoupSession` or simply enable TLS certificate verification. From quick look `g_object_set (G_OBJECT (info->session), "ssl-use-system-ca-file", TRUE, NULL);` might be enough, check documentation.

Fact is that switching from deprecated `SoupSessionAsync` to `SoupSession` gives us another serious problem.
So i will try your proposal, thanks.

**Comment by mcatanzaro** [comment]
I looked at #75, but you have three unrelated crash reports in that bug, the first two backtraces are low-quality, only the third backtrace there seems good enough to analyze, but it doesn't seem to be related to SoupSessionAsync -> SoupSessionSync at all afaik.

I recommend [reviewing the different defaults between SoupSessionAsync and SoupSessionSync](https://developer.gnome.org/libsoup/unstable/libsoup-session-porting.html). There are only a handful of changes and it shouldn't be hard to figure out which change is causing your problems.

**Comment by mcatanzaro** [comment]
And yes, `use-system-ca-file` should be sufficient to fix this bug.

But you really need to stop using SoupSessionAsync anyway, because it's gone in libsoup3.

**Comment by raveit65** [comment]
Sorry, i don't know how to fix the crash of clock-applet with `soup_session_async_new`.
Any way, i added TLS certificate verification with https://github.com/mate-desktop/libmateweather/commit/831b448c6289c76aff102e08407ddffc12084995.
Hopefully we can fix clock-applet problem in time before libsoup3 gets into distros.
For that reason i leave the report open as reminder.

**Comment by zhuyaliang** [comment]
I think it's necessary to check the close PR 
[1208](https://github.com/mate-desktop/mate-panel/pull/1208).This PR uses the old ```libmateweathe``` to fix the crash problem. We will use ```soupsession``` and [1208](https://github.com/mate-desktop/mate-panel/pull/1208) to test this problem

**Comment by zhuyaliang** [comment]
@raveit65 Good news,  [1208](https://github.com/mate-desktop/mate-panel/pull/1208) can solve the ```libmateweathe``` crash problem.
```
diff --git a/libmateweather/weather.c b/libmateweather/weather.c
index 5b7bbe4..3b7642b 100644
--- a/libmateweather/weather.c
+++ b/libmateweather/weather.c
@@ -553,9 +553,7 @@ _weather_info_fill (WeatherInfo *info,
     info->cb_data = data;
 
     if (!info->session) {
-        info->session = soup_session_async_new ();
-        soup_session_add_feature_by_type (info->session, SOUP_TYPE_PROXY_RESOLVER_DEFAULT);
-        g_object_set (G_OBJECT (info->session), "ssl-use-system-ca-file", TRUE, NULL);
+        info->session = soup_session_new ();
     }
```
If I can, I will replace the ```soup_session_async_new``` and restart to open  [1208](https://github.com/mate-desktop/mate-panel/pull/1208)

**Comment by raveit65** [comment]
`soup_session_async_new` needs to be replace before libsoup3 comes in to distros , because it is removed in libsoup3.
Feel free to open a PR for libmateweather and one for mate-panel. Than we can can test both together. But a reviewer marked a mem leak in https://github.com/mate-desktop/mate-panel/pull/1208, so this needs to be fixed for the clock applet.
